#!/bin/bash -e
# Stage 4, Step 04: Create environment configuration

echo "=== Creating environment configuration ==="

# Create daemon .env file
cat > "${ROOTFS_DIR}/opt/tau-daemon/daemon/.env" << 'ENVFILE'
# Tau Lighting Control - Daemon Configuration
# Generated by pi-gen image builder

# Database connection
DATABASE_URL=postgresql://tau_daemon:tau_lighting_db@localhost/tau_lighting

# Server settings
DAEMON_PORT=8000
DAEMON_HOST=0.0.0.0
LOG_LEVEL=INFO

# Control loop frequency (Hz)
CONTROL_LOOP_HZ=30

# Hardware settings
LABJACK_MOCK=false
OLA_MOCK=false
USE_GPIO=false

# CORS settings (allow all for local network access)
CORS_ALLOW_ALL=true
ENVFILE

chmod 600 "${ROOTFS_DIR}/opt/tau-daemon/daemon/.env"
chown 1000:1000 "${ROOTFS_DIR}/opt/tau-daemon/daemon/.env"

echo "Environment configuration created"
