#!/bin/bash
# Setup script for Tau Lighting Control System on Raspberry Pi
# Tested on Raspberry Pi 4 with Raspberry Pi OS (Debian-based)

set -e

echo "======================================"
echo "Tau Lighting System - Raspberry Pi Setup"
echo "======================================"

# Check if running on Raspberry Pi
if ! grep -q "Raspberry Pi" /proc/cpuinfo 2>/dev/null; then
    echo "⚠️  Warning: This doesn't appear to be a Raspberry Pi"
    read -p "Continue anyway? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

# Function to check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# 1. Update system packages
echo ""
echo "1. Updating system packages..."
sudo apt-get update
sudo apt-get upgrade -y

# 2. Install prerequisites
echo ""
echo "2. Installing prerequisites..."
sudo apt-get install -y \
    python3 \
    python3-venv \
    python3-pip \
    postgresql \
    postgresql-contrib \
    gcc \
    libusb-1.0-0-dev \
    git \
    curl

# Detect Python version
PYTHON_VERSION=$(python3 --version | awk '{print $2}')
echo "✓ Detected Python $PYTHON_VERSION"

# 3. Install OLA (Open Lighting Architecture)
echo ""
echo "3. Installing OLA for DMX output..."
if ! command_exists olad; then
    sudo apt-get install -y ola

    # Start OLA daemon
    sudo systemctl enable olad
    sudo systemctl start olad

    echo "✓ OLA installed and started"
    echo "  Web interface: http://localhost:9090"
else
    echo "✓ OLA already installed"
fi

# 4. LabJack USB permissions (U3-HV support)
echo ""
echo "4. Setting up LabJack USB permissions..."
sudo tee /etc/udev/rules.d/99-labjack.rules > /dev/null <<EOF
# LabJack U3-HV USB permissions
SUBSYSTEM=="usb", ATTR{idVendor}=="0cd5", ATTR{idProduct}=="0009", MODE="0666", GROUP="plugdev"
EOF

sudo udevadm control --reload-rules
sudo udevadm trigger
echo "✓ LabJack udev rules installed"

# 5. Create tau user and add to necessary groups
echo ""
echo "5. Creating tau user..."
if id "tau" &>/dev/null; then
    echo "✓ User 'tau' already exists"
else
    sudo useradd -r -m -s /bin/false -G plugdev tau
    echo "✓ Created user 'tau' with plugdev group access and home directory"
fi

# Fix permissions on tau home directory (prevents PostgreSQL SSL key errors)
sudo chown -R tau:tau /home/tau
sudo chmod 700 /home/tau
echo "✓ Fixed permissions on tau home directory"

# 6. Create installation directory
echo ""
echo "6. Setting up installation directory..."
sudo mkdir -p /opt/tau-daemon
sudo chown tau:tau /opt/tau-daemon

# Clone or update repository
cd /opt/tau-daemon
if [ -d ".git" ]; then
    echo "Repository already exists, pulling latest..."
    sudo -u tau git pull
else
    echo "Cloning Tau repository..."
    sudo -u tau git clone https://github.com/mattsoldo/tau.git .
fi

# 7. Create Python virtual environment
echo ""
echo "7. Setting up Python virtual environment..."
cd /opt/tau-daemon/daemon
if [ -d ".venv" ]; then
    echo "Virtual environment exists, updating..."
else
    sudo -u tau python3 -m venv .venv
fi

sudo -u tau .venv/bin/pip install --upgrade pip
sudo -u tau .venv/bin/pip install -r requirements.txt

# Install tau package in editable mode
echo "Installing tau package..."
sudo -u tau .venv/bin/pip install -e .

# Install OLA Python bindings manually
echo "Installing OLA Python bindings..."
sudo -u tau .venv/bin/pip install ola || echo "⚠️  OLA bindings install failed (non-critical)"

# 8. PostgreSQL database setup
echo ""
echo "8. Setting up PostgreSQL database..."

# Create database user
sudo -u postgres createuser tau_daemon 2>/dev/null || echo "Database user already exists"

# Create database
sudo -u postgres createdb tau_lighting -O tau_daemon 2>/dev/null || echo "Database already exists"

# Generate secure random password
echo ""
echo "Generating secure database password..."
DB_PASSWORD=$(openssl rand -base64 32 | tr -d "=+/" | cut -c1-25)

sudo -u postgres psql -c "ALTER USER tau_daemon WITH PASSWORD '$DB_PASSWORD';"
echo "✓ Database password generated and set"

# 9. Create environment configuration file
echo ""
echo "9. Creating environment configuration..."
cat > /tmp/tau.env <<EOF
# Tau Lighting Control System - Environment Configuration
# Generated by setup_pi.sh on $(date)

# Database Configuration
DATABASE_URL=postgresql://tau_daemon:$DB_PASSWORD@localhost/tau_lighting

# Daemon Configuration
DAEMON_PORT=8000
DAEMON_HOST=0.0.0.0
LOG_LEVEL=INFO
CONTROL_LOOP_HZ=30

# Hardware Configuration
# Set USE_GPIO=true to use Raspberry Pi GPIO pins instead of LabJack
USE_GPIO=false

# CORS Configuration (allow access from local network)
CORS_ALLOW_ALL=true
EOF

sudo mv /tmp/tau.env /opt/tau-daemon/daemon/.env
sudo chown tau:tau /opt/tau-daemon/daemon/.env
sudo chmod 600 /opt/tau-daemon/daemon/.env
echo "✓ Environment file created at /opt/tau-daemon/daemon/.env"

# 10. Run database migrations
echo ""
echo "10. Running database migrations..."
cd /opt/tau-daemon/daemon
sudo -u tau bash -c "set -a && source .env && set +a && .venv/bin/alembic upgrade head"
echo "✓ Database migrations complete"

# 11. Load example configuration (optional)
echo ""
read -p "Load example configuration (fixtures, groups, scenes)? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    sudo -u tau bash -c "set -a && source .env && set +a && .venv/bin/python scripts/load_example_config.py"
    echo "✓ Example configuration loaded"
fi

# 12. Create log directory
echo ""
echo "12. Creating log directory..."
sudo mkdir -p /var/log/tau
sudo chown tau:tau /var/log/tau
echo "✓ Log directory created"

# 13. Install systemd service
echo ""
echo "13. Installing systemd service..."
sudo cp /opt/tau-daemon/daemon/deployment/tau-daemon.service /etc/systemd/system/

# Update service file with correct database password
sudo sed -i "s|tau_password|$DB_PASSWORD|g" /etc/systemd/system/tau-daemon.service

sudo systemctl daemon-reload
sudo systemctl enable tau-daemon
echo "✓ Systemd service installed and enabled"

# 14. Install sudo configuration for updates
echo ""
echo "14. Installing sudo configuration for updates..."
sudo cp /opt/tau-daemon/daemon/deployment/tau-sudoers /etc/sudoers.d/tau-daemon
sudo chmod 0440 /etc/sudoers.d/tau-daemon
sudo chown root:root /etc/sudoers.d/tau-daemon
echo "✓ Sudo configuration installed (allows tau user to restart services)"

# 15. Test LabJack connection (if connected)
echo ""
echo "15. Testing hardware connections..."
if lsusb | grep -q "0cd5:0009"; then
    echo "✓ LabJack U3 detected"
else
    echo "⚠️  LabJack U3 not detected (connect and replug to test)"
fi

if systemctl is-active --quiet olad; then
    echo "✓ OLA daemon running"
else
    echo "⚠️  OLA daemon not running"
fi

# 16. Frontend installation (automatic)
echo ""
echo "16. Installing web frontend..."

# Get Pi's IP for build-time config
PI_IP=$(hostname -I | awk '{print $1}')

echo ""
echo "16a. Installing Node.js and npm..."

# Install Node.js 20.x (LTS)
curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
sudo apt-get install -y nodejs

echo "✓ Node.js $(node --version) installed"
echo "✓ npm $(npm --version) installed"

echo ""
echo "16b. Installing frontend dependencies..."
cd /opt/tau-daemon/frontend
sudo -u tau npm ci

echo ""
echo "16c. Building frontend..."
sudo -u tau bash -c "NEXT_PUBLIC_API_URL=http://$PI_IP:8000 NEXT_PUBLIC_WS_URL=ws://$PI_IP:8000 npm run build"

echo ""
echo "16d. Installing frontend systemd service..."
sudo cp /opt/tau-daemon/daemon/deployment/tau-frontend.service /etc/systemd/system/

# Update service with Pi's IP
sudo sed -i "s|http://localhost:8000|http://$PI_IP:8000|g" /etc/systemd/system/tau-frontend.service
sudo sed -i "s|ws://localhost:8000|ws://$PI_IP:8000|g" /etc/systemd/system/tau-frontend.service

sudo systemctl daemon-reload
sudo systemctl enable tau-frontend

echo "✓ Frontend installed and configured"

# 17. Start services (automatic)
echo ""
echo "17. Starting services..."

# Start backend
sudo systemctl start tau-daemon
sleep 3

if systemctl is-active --quiet tau-daemon; then
    echo "✓ Tau daemon started successfully"
else
    echo "❌ Tau daemon failed to start. Check logs:"
    echo "   sudo journalctl -u tau-daemon -n 50"
fi

# Start frontend
sudo systemctl start tau-frontend
sleep 2

if systemctl is-active --quiet tau-frontend; then
    echo "✓ Frontend started successfully"
else
    echo "❌ Frontend failed to start. Check logs:"
    echo "   sudo journalctl -u tau-frontend -n 50"
fi

echo ""
echo "======================================"
echo "✅ Setup Complete!"
echo "======================================"
echo ""
echo "Service Management:"
echo "  Backend:"
echo "    Start:   sudo systemctl start tau-daemon"
echo "    Stop:    sudo systemctl stop tau-daemon"
echo "    Restart: sudo systemctl restart tau-daemon"
echo "    Status:  sudo systemctl status tau-daemon"
echo "    Logs:    sudo journalctl -u tau-daemon -f"
echo ""
echo "  Frontend:"
echo "    Start:   sudo systemctl start tau-frontend"
echo "    Stop:    sudo systemctl stop tau-frontend"
echo "    Restart: sudo systemctl restart tau-frontend"
echo "    Status:  sudo systemctl status tau-frontend"
echo "    Logs:    sudo journalctl -u tau-frontend -f"

echo ""
echo "Access Points (from any device on your network):"
echo "  🌐 Web Interface:  http://$PI_IP"
echo "  📡 API:            http://$PI_IP:8000"
echo "  📚 API Docs:       http://$PI_IP:8000/docs"
echo "  💡 OLA Web UI:     http://$PI_IP:9090"
echo ""
echo "Configuration Files:"
echo "  Backend:     /opt/tau-daemon/daemon/.env"
echo "  Frontend:    /etc/systemd/system/tau-frontend.service"
echo "  Services:    /etc/systemd/system/tau-*.service"
echo "  Logs:        /var/log/tau/"
echo ""
echo "Database Password:"
echo "  The auto-generated password is stored in:"
echo "  /opt/tau-daemon/daemon/.env"
echo ""
echo "Next Steps:"
echo "  1. Connect your LabJack U3 via USB"
echo "  2. Open http://$PI_IP in your browser"
echo "  3. Configure switches, fixtures, and groups via web UI"
echo "  4. Configure DMX fixtures via OLA: http://$PI_IP:9090"
echo "  5. Test software updates: Config → Settings → Check for Updates"
echo ""
echo "======================================"
